[2024-06-01T19:27:52.571+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T19:27:52.721+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: complaints_dag_id.transform_complaints_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-06-01T19:27:52.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: complaints_dag_id.transform_complaints_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-06-01T19:27:52.809+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-01T19:27:52.839+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_complaints_task> on 2024-05-20 00:00:00+00:00
[2024-06-01T19:27:52.854+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=184) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T19:27:52.853+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'complaints_dag_id', 'transform_complaints_task', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/complaints_dag.py', '--cfg-path', '/tmp/tmp8e786zx1']
[2024-06-01T19:27:52.858+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2024-06-01T19:27:52.859+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask transform_complaints_task
[2024-06-01T19:27:52.972+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T19:27:53.498+0000] {task_command.py:426} INFO - Running <TaskInstance: complaints_dag_id.transform_complaints_task scheduled__2024-05-20T00:00:00+00:00 [running]> on host f5e3e15eb39a
[2024-06-01T19:27:58.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myowner' AIRFLOW_CTX_DAG_ID='complaints_dag_id' AIRFLOW_CTX_TASK_ID='transform_complaints_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-06-01T19:27:58.792+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T19:28:09.507+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-06-01T19:28:09.519+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-01T19:28:09.526+0000] {process_utils.py:132} INFO - Sending 15 to group 212. PIDs of all processes in the group: [212]
[2024-06-01T19:28:09.528+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 212
[2024-06-01T19:28:09.530+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-01T19:28:09.631+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T19:28:09.717+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/complaints_dag.py", line 20, in run_transform_fin_statements
    return transform_fin_statements("2023q4")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/python_scripts/transform_financial_statements.py", line 5, in transform_fin_statements
    df_num = pd.read_csv(f"/opt/airflow/data/2023q4/num.txt", sep='\t')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 617, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1748, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 843, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 904, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 879, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 890, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2050, in pandas._libs.parsers.raise_parser_error
  File "<frozen codecs>", line 331, in getstate
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-01T19:28:09.764+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=complaints_dag_id, task_id=transform_complaints_task, run_id=scheduled__2024-05-20T00:00:00+00:00, execution_date=20240520T000000, start_date=20240601T192752, end_date=20240601T192809
[2024-06-01T19:28:09.862+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=212, status='terminated', exitcode=2, started='19:27:52') (212) terminated with exit code 2
